name: linio_pretty_dio_interceptor
description: A starting point for Dart libraries or applications.
version: 0.0.6+1
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  linio: ^0.0.6+1
  pretty_dio_logger: ^1.1.1
  dio: ^4.0.6

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.21.3
